package restmodel;

import java.sql.CallableStatement;
import java.sql.Types;
import oracle.jbo.server.ApplicationModuleImpl;

import restmodel.common.RESTAppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 05 08:09:15 CST 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RESTAppModuleImpl extends ApplicationModuleImpl implements RESTAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public RESTAppModuleImpl() {
    }
    public String testComunicacion(String message){
        String llamada = "BEGIN ?:=HR.Test_PKG.Test_Comunicacion(?); END;";
        String vMessage = message;
        try {
            CallableStatement cs = getDBTransaction().createCallableStatement(llamada,0);
            cs.registerOutParameter(1,Types.VARCHAR);
            cs.setString(2,vMessage);
            cs.execute();
            String resultado = cs.getString(1);
            return resultado;
        }
            catch (Exception e) {
            return null;
        }        
    }   
}

