package restmodel.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 05 08:09:59 CST 2025
// ---------------------------------------------------------------------
public interface RESTAppModule extends ApplicationModule {
    String testComunicacion(String message);
}

